// <auto-generated />
using System;
using DeviceLicenseSaleApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceLicenseSaleApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426115614_MakeUserProfileDateOfBirthOptional")]
    partial class MakeUserProfileDateOfBirthOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Administrative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutomaticBackupDownloadQXConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutomaticFirmwareUpdatesForInstalledIPPhones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutomaticQXFirmwareUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomLanguagePackSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomizingSystemVoiceMessages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaylightSavingsTimeAdjustment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnhancedSystemLoggingSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPPhonePlugAndPlay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QXGatewaysAutoConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemoteIPPhoneSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRightManagement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoicemailSetupViaPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administratives");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.CallAnswering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoAttendantStandardCustomScenarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallHistoryAutoAttendantCustomScenario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallHunting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallPickup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallQueue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyInterrupt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtensionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotDesking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultiCompanyReceptionist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SimultaneousRing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CallAnswerings");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.CallManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallHold")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallPark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallParkOnAutoAttendant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallTransfer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallWaiting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyInterrupt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scheduling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThreeWayConferencing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CallManagements");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.CallScreening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallBlocking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectTransferToVoiceMailbox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistinctiveRinging")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoNotDisturb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HidingCallerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CallScreenings");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.CostBandwidthSaving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallAlert")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassOfService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTimeSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DialPlans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotDesking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallCallDurationLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinBarring")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfDayDialing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CostBandwidthSavings");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.DeviceTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdditionalConcurrentCallsWithKeys")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalIPPhonesWithKeys")
                        .HasColumnType("int");

                    b.Property<int>("AnalogPhones")
                        .HasColumnType("int");

                    b.Property<int>("AudioInPorts")
                        .HasColumnType("int");

                    b.Property<int>("AudioOutPorts")
                        .HasColumnType("int");

                    b.Property<int>("ConcurrentCalls")
                        .HasColumnType("int");

                    b.Property<int>("EthernetLANPorts")
                        .HasColumnType("int");

                    b.Property<int>("EthernetWANPorts")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("IPPhones")
                        .HasColumnType("int");

                    b.Property<int>("LicensableFeatureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SDSlots")
                        .HasColumnType("int");

                    b.Property<int>("TotalPhones")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("LicensableFeatureId");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Features", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministrativeId")
                        .HasColumnType("int");

                    b.Property<int>("CallAnsweringId")
                        .HasColumnType("int");

                    b.Property<int>("CallManagementId")
                        .HasColumnType("int");

                    b.Property<int>("CallScreeningId")
                        .HasColumnType("int");

                    b.Property<int>("CostBandwidthSavingId")
                        .HasColumnType("int");

                    b.Property<int>("GroupConvenienceId")
                        .HasColumnType("int");

                    b.Property<string>("HotCallAddInForMicrosoftOutlook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotKeyCall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RTPStreamingChannels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityToolsId")
                        .HasColumnType("int");

                    b.Property<int>("UnifiedCommunicationsId")
                        .HasColumnType("int");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeId");

                    b.HasIndex("CallAnsweringId");

                    b.HasIndex("CallManagementId");

                    b.HasIndex("CallScreeningId");

                    b.HasIndex("CostBandwidthSavingId");

                    b.HasIndex("GroupConvenienceId");

                    b.HasIndex("SecurityToolsId");

                    b.HasIndex("UnifiedCommunicationsId");

                    b.HasIndex("UtilityId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.GroupConvenience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alarm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedPhones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoRedial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallPaging")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallbackOnAutoAttendant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClickToCallChromeExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomizingSystemVoiceMessages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DialAndAnnounce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyInterrupt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalSpeedDialDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoldMusic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotDesking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPPhonesLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intercom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentChildExtensionConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkAndPage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneBook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceptionistPhoneConfigurationWizard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scheduling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeedDial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebRtcClick2Call")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupConveniences");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.LicensableFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AdvancedProxyConnectionService")
                        .HasColumnType("bit");

                    b.Property<int?>("AudioConferenceBridge")
                        .HasColumnType("int");

                    b.Property<bool?>("AutoDialerActivation")
                        .HasColumnType("bit");

                    b.Property<int?>("AutoDialerExpansionKey")
                        .HasColumnType("int");

                    b.Property<bool?>("AutomaticCallDistributionACD")
                        .HasColumnType("bit");

                    b.Property<bool?>("AutomaticOutboundCallingAOC")
                        .HasColumnType("bit");

                    b.Property<bool?>("BargeIn")
                        .HasColumnType("bit");

                    b.Property<bool?>("CRMIntegration")
                        .HasColumnType("bit");

                    b.Property<int?>("CallRecording")
                        .HasColumnType("int");

                    b.Property<bool?>("CallingCostControl")
                        .HasColumnType("bit");

                    b.Property<int?>("ConcurrentCallExpansion")
                        .HasColumnType("int");

                    b.Property<int?>("EpygiACDConsoleEAC")
                        .HasColumnType("int");

                    b.Property<int?>("IPPhoneExpansionKey")
                        .HasColumnType("int");

                    b.Property<bool?>("PCCActivationLicense")
                        .HasColumnType("bit");

                    b.Property<bool?>("ServerSystemRedundancyActivation")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextToSpeechTranscription")
                        .HasColumnType("bit");

                    b.Property<bool?>("ThirdPartyCallControl3PCC")
                        .HasColumnType("bit");

                    b.Property<int?>("VideoConferenceBridge")
                        .HasColumnType("int");

                    b.Property<bool?>("VoiceEnabledAutoAttendant")
                        .HasColumnType("bit");

                    b.Property<int?>("VoiceMailCallRecordingTranscription")
                        .HasColumnType("int");

                    b.Property<int?>("eQallReceptionistConsole")
                        .HasColumnType("int");

                    b.Property<int?>("eQallSMSWhatsAppMessaging")
                        .HasColumnType("int");

                    b.Property<int?>("eQallSoftphone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LicensableFeatures");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AdvancedProxyConnectionService")
                        .HasColumnType("bit");

                    b.Property<int?>("AudioConferenceBridge")
                        .HasColumnType("int");

                    b.Property<bool?>("AutoDialerActivation")
                        .HasColumnType("bit");

                    b.Property<int?>("AutoDialerExpansionKey")
                        .HasColumnType("int");

                    b.Property<bool?>("AutomaticCallDistributionACD")
                        .HasColumnType("bit");

                    b.Property<bool?>("AutomaticOutboundCallingAOC")
                        .HasColumnType("bit");

                    b.Property<bool?>("BargeIn")
                        .HasColumnType("bit");

                    b.Property<bool?>("CRMIntegration")
                        .HasColumnType("bit");

                    b.Property<int?>("CallRecording")
                        .HasColumnType("int");

                    b.Property<bool?>("CallingCostControl")
                        .HasColumnType("bit");

                    b.Property<int?>("ConcurrentCallExpansion")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpygiACDConsoleEAC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IPPhoneExpansionKey")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PCCActivationLicense")
                        .HasColumnType("bit");

                    b.Property<bool?>("ServerSystemRedundancyActivation")
                        .HasColumnType("bit");

                    b.Property<bool?>("TextToSpeechTranscription")
                        .HasColumnType("bit");

                    b.Property<bool?>("ThirdPartyCallControl3PCC")
                        .HasColumnType("bit");

                    b.Property<int?>("VideoConferenceBridge")
                        .HasColumnType("int");

                    b.Property<bool?>("VoiceEnabledAutoAttendant")
                        .HasColumnType("bit");

                    b.Property<int?>("VoiceMailCallRecordingTranscription")
                        .HasColumnType("int");

                    b.Property<int?>("eQallReceptionistConsole")
                        .HasColumnType("int");

                    b.Property<int?>("eQallSMSWhatsAppMessaging")
                        .HasColumnType("int");

                    b.Property<int?>("eQallSoftphone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.SecurityTools", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallAlert")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassOfService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTimeSettings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firewall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallCallDurationLimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinBarring")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecuringCallRouting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecuringCallsOnAutoAttendant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SipIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemSecurityDiagnostics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemSecuritySoftware")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRightsManagement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecurityTools");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.UnifiedCommunications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallForwarding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallRelay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FindMeFollowMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surveillance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnifiedMessaging")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoicemailService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnifiedCommunications");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoldMusic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T38FaxFaxRelayClearChannelFax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilities");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Building", b =>
                {
                    b.HasOne("DeviceLicenseSaleApi.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Device", b =>
                {
                    b.HasOne("DeviceLicenseSaleApi.Models.DeviceTypes", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.License", "License")
                        .WithMany("Devices")
                        .HasForeignKey("LicenseId");

                    b.HasOne("DeviceLicenseSaleApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");

                    b.Navigation("License");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.DeviceTypes", b =>
                {
                    b.HasOne("DeviceLicenseSaleApi.Models.Features", "Features")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.LicensableFeatures", "LicensableFeatures")
                        .WithMany()
                        .HasForeignKey("LicensableFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Features");

                    b.Navigation("LicensableFeatures");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.Features", b =>
                {
                    b.HasOne("DeviceLicenseSaleApi.Models.Administrative", "Administrative")
                        .WithMany()
                        .HasForeignKey("AdministrativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.CallAnswering", "CallAnswering")
                        .WithMany()
                        .HasForeignKey("CallAnsweringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.CallManagement", "CallManagement")
                        .WithMany()
                        .HasForeignKey("CallManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.CallScreening", "CallScreening")
                        .WithMany()
                        .HasForeignKey("CallScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.CostBandwidthSaving", "CostBandwidthSaving")
                        .WithMany()
                        .HasForeignKey("CostBandwidthSavingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.GroupConvenience", "GroupConvenience")
                        .WithMany()
                        .HasForeignKey("GroupConvenienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.SecurityTools", "SecurityTools")
                        .WithMany()
                        .HasForeignKey("SecurityToolsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.UnifiedCommunications", "UnifiedCommunications")
                        .WithMany()
                        .HasForeignKey("UnifiedCommunicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.Utility", "Utility")
                        .WithMany()
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrative");

                    b.Navigation("CallAnswering");

                    b.Navigation("CallManagement");

                    b.Navigation("CallScreening");

                    b.Navigation("CostBandwidthSaving");

                    b.Navigation("GroupConvenience");

                    b.Navigation("SecurityTools");

                    b.Navigation("UnifiedCommunications");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.User", b =>
                {
                    b.HasOne("DeviceLicenseSaleApi.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceLicenseSaleApi.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.UserProfile", b =>
                {
                    b.HasOne("DeviceLicenseSaleApi.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("DeviceLicenseSaleApi.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeviceLicenseSaleApi.Models.License", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
